# exception

n = 4
z = 0

try:
    print("Before")
    r = n / z
    print("After")
except:
    print("Exception happened")

print("Done")
